### ISSUE TITLE
Result of the document content is not updated

### ISSUE THREAD

**Issue by chqu1012** [miho/MonacoFX#12]
After editing some text in monacofx, I tried to get the result of the document, but for some times, it doesn't represents the whole text by calling Document#getText(). I added a another method to get the text value and this seems to work
```java
public class Document{
...
    public String getValue() {
    	 return (String) editor.call("getValue");
    }
}
```

In some case this method wasn't called.
```
 window.setMember("contentChangeListener", new JFunction( args -> {

            String text = (String) editor.call("getValue");
            if(text!=null) {
                setText(text);
                numberOfLinesProperty.setValue(text.split("\\R").length);
            }
            return null;
        }));

```

**Comment by miho** [comment]
It looks like this issue is caused by this https://www.hissenit.com/javafx-webview-webkit-fehler-javascript-java-kommunikation-java-8-frank-hissen-it-blog.html

We will keep a reference to the callback function. this should fix the issue.
