### ISSUE TITLE
text property doesn't change

### ISSUE THREAD

**Issue by DerekL0576** [miho/MonacoFX#30]
When you type in the editor, it doesn't update the text property. So getEditor().getDocument().getText() either returns null or whatever text you manually set with setText().

It makes this whole thing pretty much useless.

**Comment by DerekL0576** [comment]
To work around this issue I made these changes to [src/main/java/eu/mihosoft/monacofx/Document.java](https://github.com/miho/MonacoFX/blob/master/src/main/java/eu/mihosoft/monacofx/Document.java)

```
void setEditor(WebEngine engine, JSObject window, JSObject editor) {
....
    // initial text
    editor.call("setValue", textProperty.get());

    // text changes -> js
    textProperty.addListener((ov) -> {
        if (!updatingText) editor.call("setValue", textProperty.get());
    });
....
}
```

```
public String getText() {
    String text = (String) editor.call("getValue");
    try {
        updatingText = true;
        textProperty().set(text);
    } finally {
        updatingText = false;
    }
    numberOfLinesProperty.setValue(text.split("\\R").length);
    return text;
}
```

It's not perfect, but I can at least set the text and get the edited changes to save to file.  The contentChangeListener is never triggered so I still can't get changed notifications.

**Comment by EasyG0ing1** [comment]
@DerekL0576 
```Java
MonacoFX mfx = new	MonacoFX();
mfx.getEditor().getDocument().textProperty().addListener((observable, oldValue, newValue) -> {
			if (newValue != null)
				mfx.setText(newValue);
		});

**Comment by DerekL0576** [comment]
Thanks @EasyG0ing1.  

I can see now that we need to set a listener on the textProperty for the contentChangeListener to get triggered.  The listener doesn't actually have to do anything, it works fine with an empty lambda function.

` monacoFX.getEditor().getDocument().textProperty().addListener((observable, oldValue, newValue) -> {});`

Weird, but it works. 👍

**Comment by DerekL0576** [comment]
I actually found the real cause of my problem. I had to add `exports eu.mihosoft.monacofx;` to my module-info.   I added it after my initial workaround and inadvertently fixed the original problem without realising. My bad.

**Comment by EasyG0ing1** [comment]
> Thanks @EasyG0ing1.
> 
> I can see now that we need to set a listener on the textProperty for the contentChangeListener to get triggered. The listener doesn't actually have to do anything, it works fine with an empty lambda function.
> 
> ` monacoFX.getEditor().getDocument().textProperty().addListener((observable, oldValue, newValue) -> {});`
> 
> Weird, but it works. 👍

Thats Interesting ... never tried it with an empty listener before.

**Comment by EasyG0ing1** [comment]
> I actually found the real cause of my problem. I had to add `exports eu.mihosoft.monacofx;` to my module-info. I added it after my initial workaround and inadvertently fixed the original problem without realising. My bad.

@DerekL0576 That kinda makes sense ... though it shouldn't be required.
