### ISSUE TITLE
Published artifact adds dependency on JavaFX for Windows

### ISSUE THREAD

**Issue by jperedadnr** [miho/MonacoFX#6]
When using the library on Mac or Linux, JavaFX 12.0.1-win artifacts are included, which is not convenient.

This happens because the [pom](https://bintray.com/miho/MonacoFX/download_file?file_path=eu%2Fmihosoft%2Fmonacofx%2Fmonacofx%2F0.0.2%2Fmonacofx-0.0.2.pom) has these dependencies:

```
<dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-graphics</artifactId>
      <version>12.0.1</version>
      <classifier>win</classifier>
      <scope>runtime</scope>
    </dependency>
...
```
that include the win classifier.

One way to avoid it is to remove the classifiers from the generated pom (see for instance [this](https://github.com/gluonhq/attach/blob/master/gradle/mavenPublish.gradle#L109)). Removing the classifier from the pom is not a problem, once in a given platform Maven will resolve the required classifier.

**Comment by miho** [comment]
I just verified it. Especially, the jfx-web dependency is quite annoying. Can you create a PR for this? Thanks for letting me know.

**Comment by jperedadnr** [comment]
Ok, done!
