### ISSUE TITLE
Editor does not return the right text.

### ISSUE THREAD

**Issue by lnbmc** [miho/MonacoFX#7]
When i am typing in my textbox, when a key combination is pressed, it should execute the following code: 

```java
System.out.println(txtContent.getEditor().getDocument().getText());
```
(txtContent is the MonaxoFX)

What i type in the textbox is this:
![error1](https://user-images.githubusercontent.com/59974160/74916319-ef7f9500-53c5-11ea-94f7-73e3a1bf0aa1.PNG)

But my console output is like this: 
![error2](https://user-images.githubusercontent.com/59974160/74916341-f908fd00-53c5-11ea-9ea8-f48e785de879.PNG)

**Comment by miho** [comment]
Unfortunately, I can't reproduce this behavior. If you can't solve it, please share more details like OS, Java and JavaFX versions used to runh the application. Additionally some sample code based on the tutorial app would be great.

**Comment by miho** [comment]
Closed due to inactivity.
